#https://cloud.spring.io/spring-cloud-gateway/reference/html/
server:
  port: 8088

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"