server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

springcloud:
  cassandra:
    url: localhost
    port: 9042
    keyspace:
      name: springcloud
    username: cassandra
    password: cassandra


