server:
  port: 8502

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: emrcnort
    password: emrcnort


queue:
  rabbitmq:
    exchange: default
    name: msqueue
    routingKey: routingkey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka


